import datetime as dt
# Cycle Status
STATUS_NEW = 'NEW'
STATUS_OPEN = 'OPEN'
STATUS_CLOSED = 'CLOSED'

# Trade Roles
ROLE_HEDGE = 'HEDGE'
ROLE_INCOME = 'INCOME' # The daily spread

# Leg side: long/short
LEG_SIDE_SHORT = "short"
LEG_SIDE_LONG = "long"

# Automation States (The decisions made by server_libs)
STATE_PANIC_HARVEST = 'PANIC_HARVEST'
STATE_ROLL_REQUIRED = 'ROLL_REQUIRED'
STATE_HARVEST_TARGET_HIT = 'HARVEST_TARGET_HIT'
STATE_HEDGE_MISSING = 'HEDGE_MISSING'
STATE_SPREAD_MISSING = 'SPREAD_MISSING'
STATE_HEDGE_TOO_WEAK = 'HEDGE_TOO_WEAK' # Delta < 15
STATE_HEDGE_ADJUSTMENT_NEEDED = 'HEDGE_ADJUSTMENT_NEEDED' # New
STATE_IDLE = 'IDLE'

# Alert Levels
ALERT_CRITICAL = 'CRITICAL'
ALERT_INFO = 'INFO'

# Tradier API enums
TRADIER_OPTION_TYPE_PUT = 'put'
TRADIER_OPTION_TYPE_CALL = 'call'

# Misc statics
MARKET_OPEN_TIME = dt.time(9, 30)
