# Cycle Status
STATUS_NEW = 'NEW'
STATUS_OPEN = 'OPEN'
STATUS_CLOSED = 'CLOSED'

# Trade Roles
ROLE_HEDGE = 'HEDGE'
ROLE_INCOME = 'INCOME' # The daily spread

# Automation States (The decisions made by server_libs)
STATE_PANIC_HARVEST = 'PANIC_HARVEST'
STATE_ROLL_REQUIRED = 'ROLL_REQUIRED'
STATE_HARVEST_TARGET_HIT = 'HARVEST_TARGET_HIT'
STATE_HEDGE_MISSING = 'HEDGE_MISSING'
STATE_SPREAD_MISSING = 'SPREAD_MISSING'
STATE_HEDGE_TOO_WEAK = 'HEDGE_TOO_WEAK' # Delta < 15
STATE_IDLE = 'IDLE'

# Alert Levels
ALERT_CRITICAL = 'CRITICAL'
ALERT_INFO = 'INFO'
