unique_ids:
  assets:
    IKTC_logo.png: '1761762660501464223512344.869'
    standard-page.html: COG33JER6VENYUAY74647QSQCSUL6BYS
    theme.css: 4XDJBN2D4JZ4VCXYJSTVMDKJG4SNMPCS
  forms:
    Form1: TYH7STFVFCYUCFYDK5DQ7IODEGK5GXA7
  modules: {}
  scripts: {}
  server_modules: {}
